// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBon5F7PHhWIKAYpHs02L6kBQbxyLYOi-4',
    appId: '1:706850476270:web:f7a2e145b41d0ec6e523ff',
    messagingSenderId: '706850476270',
    projectId: 'fazacademie',
    authDomain: 'fazacademie.firebaseapp.com',
    storageBucket: 'fazacademie.firebasestorage.app',
    measurementId: 'G-FVGJECFM0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsMDLl0fP7Nvo4SpjXksg_vsugF8rnzWM',
    appId: '1:706850476270:android:b0de3e02fb36db16e523ff',
    messagingSenderId: '706850476270',
    projectId: 'fazacademie',
    storageBucket: 'fazacademie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgC1gu2r76JJyYGD2yc3pIbkeMcrb-rE',
    appId: '1:706850476270:ios:9d1fc7db969424a8e523ff',
    messagingSenderId: '706850476270',
    projectId: 'fazacademie',
    storageBucket: 'fazacademie.firebasestorage.app',
    iosBundleId: 'com.example.adminFazacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgC1gu2r76JJyYGD2yc3pIbkeMcrb-rE',
    appId: '1:706850476270:ios:9d1fc7db969424a8e523ff',
    messagingSenderId: '706850476270',
    projectId: 'fazacademie',
    storageBucket: 'fazacademie.firebasestorage.app',
    iosBundleId: 'com.example.adminFazacademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBon5F7PHhWIKAYpHs02L6kBQbxyLYOi-4',
    appId: '1:706850476270:web:4b7dfb0301358d77e523ff',
    messagingSenderId: '706850476270',
    projectId: 'fazacademie',
    authDomain: 'fazacademie.firebaseapp.com',
    storageBucket: 'fazacademie.firebasestorage.app',
    measurementId: 'G-70D97KZ2GG',
  );

}